package it.denzosoft.jvmmonitor.agent.instrument.web;

/**
 * Holds the JavaScript snippet that gets auto-injected into HTML pages.
 * Captures: clicks, navigations, AJAX/fetch calls, JS errors, page load timing.
 * Sends beacons to /jvmmonitor-beacon via POST.
 */
public final class BeaconScript {

    private BeaconScript() {}

    public static final String SCRIPT = "<script data-jvmmonitor=\"true\">\n"
        + "(function(){\n"
        + "  if(window.__jvmmon) return;\n"
        + "  window.__jvmmon=true;\n"
        + "  var B='/jvmmonitor-beacon';\n"
        + "  var sid=Math.random().toString(36).substr(2,9);\n"
        + "  var seq=0;\n"
        + "\n"
        + "  function send(type,data){\n"
        + "    try{\n"
        + "      var e={t:type,ts:Date.now(),sid:sid,seq:seq++,url:location.href,d:data};\n"
        + "      var x=new XMLHttpRequest();\n"
        + "      x.open('POST',B,true);\n"
        + "      x.setRequestHeader('Content-Type','application/json');\n"
        + "      x.send(JSON.stringify(e));\n"
        + "    }catch(ex){}\n"
        + "  }\n"
        + "\n"
        + "  /* Page load timing */\n"
        + "  window.addEventListener('load',function(){\n"
        + "    var p=performance.timing;\n"
        + "    send('pageload',{\n"
        + "      dns:p.domainLookupEnd-p.domainLookupStart,\n"
        + "      tcp:p.connectEnd-p.connectStart,\n"
        + "      ttfb:p.responseStart-p.requestStart,\n"
        + "      dom:p.domContentLoadedEventEnd-p.navigationStart,\n"
        + "      load:p.loadEventEnd-p.navigationStart,\n"
        + "      title:document.title\n"
        + "    });\n"
        + "  });\n"
        + "\n"
        + "  /* Click tracking */\n"
        + "  document.addEventListener('click',function(e){\n"
        + "    var el=e.target;\n"
        + "    var tag=el.tagName;\n"
        + "    var id=el.id||'';\n"
        + "    var cls=el.className||'';\n"
        + "    if(typeof cls!=='string')cls='';\n"
        + "    var text=(el.textContent||el.innerText||'').substr(0,50).trim();\n"
        + "    var href=el.href||(el.closest&&el.closest('a')&&el.closest('a').href)||'';\n"
        + "    send('click',{tag:tag,id:id,cls:cls.substr(0,80),text:text,href:href||''});\n"
        + "  },true);\n"
        + "\n"
        + "  /* AJAX interception (XMLHttpRequest) */\n"
        + "  var origOpen=XMLHttpRequest.prototype.open;\n"
        + "  var origSend=XMLHttpRequest.prototype.send;\n"
        + "  XMLHttpRequest.prototype.open=function(m,u){\n"
        + "    if(u!==B){this._jm={m:m,u:u,t0:Date.now()};}\n"
        + "    return origOpen.apply(this,arguments);\n"
        + "  };\n"
        + "  XMLHttpRequest.prototype.send=function(){\n"
        + "    var self=this;\n"
        + "    if(self._jm){\n"
        + "      self._jm.t0=Date.now();\n"
        + "      self.addEventListener('loadend',function(){\n"
        + "        var dur=Date.now()-self._jm.t0;\n"
        + "        send('ajax',{method:self._jm.m,url:self._jm.u,status:self.status,dur:dur});\n"
        + "      });\n"
        + "    }\n"
        + "    return origSend.apply(this,arguments);\n"
        + "  };\n"
        + "\n"
        + "  /* Fetch interception */\n"
        + "  if(window.fetch){\n"
        + "    var origFetch=window.fetch;\n"
        + "    window.fetch=function(url,opts){\n"
        + "      var t0=Date.now();\n"
        + "      var method=(opts&&opts.method)||'GET';\n"
        + "      var u=(typeof url==='string')?url:url.url||'';\n"
        + "      if(u===B) return origFetch.apply(this,arguments);\n"
        + "      return origFetch.apply(this,arguments).then(function(r){\n"
        + "        send('fetch',{method:method,url:u,status:r.status,dur:Date.now()-t0});\n"
        + "        return r;\n"
        + "      }).catch(function(e){\n"
        + "        send('fetch',{method:method,url:u,status:0,dur:Date.now()-t0,err:e.message});\n"
        + "        throw e;\n"
        + "      });\n"
        + "    };\n"
        + "  }\n"
        + "\n"
        + "  /* JavaScript error tracking */\n"
        + "  window.addEventListener('error',function(e){\n"
        + "    send('jserror',{msg:e.message||'',file:e.filename||'',line:e.lineno||0,col:e.colno||0});\n"
        + "  });\n"
        + "  window.addEventListener('unhandledrejection',function(e){\n"
        + "    send('jserror',{msg:'Unhandled Promise: '+(e.reason?e.reason.message||e.reason:'unknown'),file:'',line:0,col:0});\n"
        + "  });\n"
        + "\n"
        + "  /* Navigation tracking (SPA) */\n"
        + "  var lastUrl=location.href;\n"
        + "  setInterval(function(){\n"
        + "    if(location.href!==lastUrl){\n"
        + "      send('navigate',{from:lastUrl,to:location.href});\n"
        + "      lastUrl=location.href;\n"
        + "    }\n"
        + "  },500);\n"
        + "\n"
        + "  /* Form submit tracking */\n"
        + "  document.addEventListener('submit',function(e){\n"
        + "    var form=e.target;\n"
        + "    send('submit',{action:form.action||'',method:form.method||'GET',id:form.id||''});\n"
        + "  },true);\n"
        + "\n"
        + "})();\n"
        + "</script>\n";
}
